### ISSUE TITLE
Improve the quality of cards

### ISSUE THREAD

**Issue by devsargam** [gdsc-fetju/api-collection#10]
The current implementation for API Card is not satisfactory and doesn't look good.
This should be improved.

Also, this should be implemented alongside with #7

**Comment by Insomniac2904** [comment]
Assign it to me. will be tweaking card UI little-bit

**Comment by devsargam** [comment]
@Insomniac2904 raise a PR. I'll assign you then.

**Comment by devsargam** [comment]
@Insomniac2904 are you working on this?
I created a mock UI for something that we can work on. Can you design cards in this format?
<img width="794" alt="image" src="https://github.com/gdsc-fetju/api-collection/assets/76874341/303a693e-c5e4-495d-8ee2-4886b7848a80">

If not feel free to say NO!

**Comment by Ryrahul** [comment]
@rajksd01
@subigya-js

**Comment by Insomniac2904** [comment]
Sorry Currently Out of Town. Cant work on it . 

> @Insomniac2904 are you working on this? I created a mock UI for something that we can work on. Can you design cards in this format? <img alt="image" width="794" src="https://user-images.githubusercontent.com/76874341/273579220-303a693e-c5e4-495d-8ee2-4886b7848a80.png">
> 
> If not feel free to say NO!

**Comment by rajksd01** [comment]
@devsargam @Ryrahul  made a pr, please review it and let me know if an edit is required!

**Comment by Ryrahul** [comment]
@devsargam  is reviewing the PR , looks good though!!

**Comment by devsargam** [comment]
Fixed in #23 by @rajksd01!
