### ISSUE TITLE
Implement dark and light mode toggle

### ISSUE THREAD

**Issue by devsargam** [gdsc-fetju/api-collection#24]
Currently the website is only using light mode.

Requirements:
- [ ] Create a toggle button in the navbar just next to github icon
- [ ] The toggle button itself should change to black on light and vice versa
- [ ] Toggle button should change the entire website to dark if light or vice versa

Currently:
<img width="505" alt="image" src="https://github.com/gdsc-fetju/api-collection/assets/76874341/237e40f6-fb77-4417-a392-8d20447eaf18">

Expected:
<img width="384" alt="image" src="https://github.com/gdsc-fetju/api-collection/assets/76874341/c5f728ca-a0b9-46f3-b91e-ed407aa09810">

Take the toggle icon from:
https://www.svgrepo.com/svg/348420/night-mode

**Comment by richmondnkrumah** [comment]
Can you assign this to me?

**Comment by Harsh-00** [comment]
Hello, I'm interested in working on this issue. Could you please assign it to me?

**Comment by devsargam** [comment]
@Harsh-00 on fcfs basis I gave this issue to @Arkhein6. But keep an eye on this if he doesn't you can raise a pr.
