### ISSUE TITLE
Create a search bar and a filter for all APIs

### ISSUE THREAD

**Issue by devsargam** [gdsc-fetju/api-collection#7]
Your task would be to:
- [ ] create a search bar for searching individual API
- [ ] create some filtering mechanism for APIs
- [ ] adding pagination for displaying all APIs

**Comment by nawinsharma** [comment]
I want to work on this issue. Can you assign me?

**Comment by devsargam** [comment]
@NawinKumarSharma assigned. LMK if you have any queries
